service: gobus-laravel

provider:
  name: aws
  region: us-east-1
  runtime: php-81

functions:
  web:
    handler: public/index.php
    layers:
      - 'arn:aws:lambda:us-east-1:209497400698:layer:php-81-fpm:11'
    events:
      - http: '*'